### ISSUE TITLE
Feature Request: iOXMidi companion app integration

### ISSUE THREAD

**Issue by objectkit** [sieren/ioxaudio#1]
http://www.s-r-n.de/midile/

Possible?

**Comment by sieren** [comment]
good point! definitely possible. would it be sufficient to open the device browser in a new view from within MIDI LE USB? not sure if I can cram that view into the dropdown menu additionally to whats there already

**Comment by objectkit** [comment]
Hurrah for possibilities! Boo for my feature greed - I didn't consider the view! I hear you. I suppose an integrated composite view? But that would break the paradigm and involve one combined audio/midi app... Hmmm. I'll get the chance to check both out and propose something here in a while...

**Comment by objectkit** [comment]
Ok - unfortunately I only have my work machine to hand, El Capitan, and not my studio machine, Mavericks, which is out of scope anyhow :(. 

A quick test of Garageband on El Capitan, and both audio and midi work fine! I created an aggregate audio device using iPhone and Built-In via Audio MIDI Setup. I used Arpist on iOS to output a sequence to a GB instrument track, and recorded Animoog on iOS to GB on an audio track via the aggregate. Simples! When connected by USB, OS X is reported as USB IDAP Out. Unfortunately there was no audio input on the iPhone so I couldn't test recording GB out to AudioShare on iOS. Is audio input on iOS supported (USB IDAP In?)?  Using default settings, audio was coming in at 24-bit 44.1 kHz which was good. I can try higher sample rates using an external audio interface at a later point... that would be supported to? (higher sample rates?)

Back to views...

In terms of view, as the views are so simple in MIDILE and iOXAudio, would it be a problem to perhaps add two buttons beneath the iPhone icon in iOXAudio, one for MIDI, one for Audio? E.g. 'Connect Audio' and 'Connect MIDI'? 

Or simply leaving a connect/disconnect button as is, with a MIDI and Audio connection status light underneath the iPhone icon? Its only informative in terms of view, so would that work?

Great work :+1: 

**Update** 
Higher sample rates are supported. Just had to switch the sample rate on built-in before using the aggregate device :+1: :+1:

**Comment by sieren** [comment]
@objectkit Unfortunately there's no IDAP IN yet, all of this is completely in the hands of Apple. Fingers crossed they do something for their next OS iteration (I guess the addition of this feature was an early indicator of the now more wire-spread rumors of making the headphone jack disappear).

As for MIDI LE. My current idea is adding a button to open up a separate device view.
![screen shot 2016-02-04 at 22 05 28](https://cloud.githubusercontent.com/assets/5174440/12829662/997a87c6-cb8b-11e5-8dd4-88b63776464e.png)

This is easiest and probably makes most sense for usability (there's no need for a special view for MIDI related things, although while I'm add it, I might add functionality to enable Bluetooth MIDI from the same view as well).

**Comment by sieren** [comment]
@objectkit released a new version of midimittr USB:
http://www.s-r-n.de/midile/appcast/midileusbrecent.zip

Let me know how this works for you :)
