### ISSUE TITLE
iPad Mini

### ISSUE THREAD

**Issue by nicknikolov** [sieren/ioxaudio#2]
Hi there! Thanks for making this.

When I plug in my iPad Mini I get a red ! icon and it doesn't let me enable it. Any ideas what's wrong?

Thanks
Nick

**Comment by sieren** [comment]
Hey @nicknikolov,

unfortunately Apple specifies that Inter-Device-Audio only works for devices with Lightning Cable with the notable exception of the very first iPad Mini [1]. In this case you might wanna try StudioMux or MusicIO as alternatives.

<img width="1301" alt="screen shot 2016-04-04 at 14 59 03" src="https://cloud.githubusercontent.com/assets/5174440/14248619/d235628e-fa75-11e5-96e2-12eb8dd817c0.png">

[1]  http://devstreaming.apple.com/videos/wwdc/2015/507pq8rldk/507/507_whats_new_in_core_audio.pdf
